import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:gnosis_chat/features/auth/domain/user_entity.dart';
import 'package:gnosis_chat/features/auth/presentation/auth_provider.dart';

/// Global provider for the currently logged-in user.
/// Derived from AuthState — single source of truth.
///
/// Note: AuthState getters are generated by Freezed (build_runner).
/// Run: flutter pub run build_runner build --delete-conflicting-outputs
final userProvider = Provider<UserEntity?>((ref) {
  final authState = ref.watch(authProvider);
  // maybeWhen is Freezed-generated; will work after build_runner
  return authState.maybeWhen(
    authenticated: (user) => user,
    orElse: () => null,
  );
});
